- hosts: "all"
  vars:
   
    mysql_root_password: "unsecure"

    wgDBserver: "localhost"
    wgDBname: "my_wiki"
    wgDBuser: "wikidbuser"
    wgDBpassword: "wikidbpass"

    ##Name and password for the admin user of the wiki
    ## !! Do not change these
    mw_admin_user: "wikiuser"
    mw_admin_password: "wikipassword"
    
    wgSitename: "RUC-APS Wiki"

    #These two are used to build wgServer
    #port, if not empty, should include the preceeding colon/:
    wikihost: "rucaps-wp10-test.lifia.info.unlp.edu.ar"
    wikiport: "" 

    #Parsoid configuration
    parsoidhost: "rucaps-wp10-test.lifia.info.unlp.edu.ar"
    #does not include the preceeding colon/: 
    parsoidport: "8000"

  # gather_facts: False
  tasks:
    - include_tasks: tasks/prepare_server.yml
    - include_tasks: tasks/install_parsoid.yml
    - include_tasks: tasks/install_smw.yml
