#install parsoid
  
- name: Extract installed parsoid to /opt/parsoid
  become: true
  unarchive:
    src: ./libs/parsoid-20171217-installed.tgz
    dest: "{{ parsoidLocation }}"
    group: www-data
    owner: www-data

- name: Copy config.yaml.jinja2 to {{ parsoidLocation }}/parsoid/config.yaml
  become: true
  template:
    src: ./templates/config.yaml.jinja2
    dest: "{{ parsoidLocation }}/parsoid/config.yaml"
    group: www-data
    owner: www-data


- name: Copy init.d script
  become: true
  template:
    src: ./templates/parsoid.service.jinja2
    dest: /etc/systemd/system/parsoid.service
    owner: root
    group: root
    mode: ug+x

- name: Register parsoid at Systemd for restarts
  become: true
  command: /bin/systemctl enable /etc/systemd/system/parsoid.service

- name: make sure parsoid is running 
  become: true
  service: 
    name: parsoid 
    state: started
